tiny: 
 checkpoint: sam2_hiera_tiny.pt
 config: sam2_hiera_t.yaml
small: 
 checkpoint: sam2_hiera_small.pt
 config: sam2_hiera_s.yaml
base_plus: 
 checkpoint: sam2_hiera_base_plus.pt
 config: sam2_hiera_b+.yaml
large: 
 checkpoint: sam2_hiera_large.pt
 config: sam2_hiera_l.yaml